---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: l2geth
spec:
  replicas: 1
  serviceName: l2geth
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      initContainers:
        - name: wait-for-deployer
          image: nicolaka/netshoot
          command: ['bash', '-c', '/script/wait/wait-for-deployer.sh']
          envFrom:
            - configMapRef:
                name: common
          volumeMounts:
            - name: wait-scripts
              mountPath: /script/wait
        - name: wait-for-dtl
          image: nicolaka/netshoot
          command: ['bash', '-c', '/script/wait/wait-for-dtl.sh']
          envFrom:
            - configMapRef:
                name: common
          volumeMounts:
            - name: wait-scripts
              mountPath: /script/wait
      containers:
        - name: l2geth
          image: onthertech/optimism.l2geth
          command: ['sh', './geth.sh']
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8545
              protocol: TCP
            - containerPort: 8546
              protocol: TCP
          resources: {}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: l2geth
            - secretRef:
                name: secret
          volumeMounts:
            - name: liveliness-script
              mountPath: /script/liveliness
            - name: l2geth-data
              mountPath: /geth
          livenessProbe:
            exec:
              command:
                - /script/liveliness/test.sh
                - geth
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: l2geth-data
          emptyDir: {}
        - name: liveliness-script
          configMap:
            name: liveliness-script
            defaultMode: 0777
        - name: wait-scripts
          configMap:
            name: wait-scripts
            defaultMode: 0777
